/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.Arc2D;
import java.util.*;
import java.io.*;
import java.net.*;
import javax.swing.Timer;

/**
 *
 * @author Gautam
 */
public class MultiplayerOptions extends javax.swing.JFrame {

    ArrayList clientOutputStreams; // stores all the output streams of the other players
    ArrayList users; // stores the ip of each user
    String own_ip; // stores your own ip
    int connectToEveryone = 0; //differentiates host to other users
    String host_ip; // stores the host ip
    int playerNumber; // the position of the player on the board
    MultiplayerBoard board; // board that is initialized once the game starts
    Timer timer; // fires at every time specified by the delay
    private final int DELAY = 18;
    long lastLoopTime;
    int[][] bats = {{180,385},{385,180},{180,5},{5,180}}; // positions for the bats
    float[] ball = {200,200}; //positions for the ball
    float[] ballv = {2,-3};

    /**
     * Creates new form MultiplayerOptions
     */
    public MultiplayerOptions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        createButton = new javax.swing.JButton();
        joinButton = new javax.swing.JButton();
        IPtext = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        msg_area = new javax.swing.JTextArea();
        connectButton = new javax.swing.JButton();
        startButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        createButton.setText("Create Lobby");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        joinButton.setText("Join Lobby");
        joinButton.setToolTipText("");
        joinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinButtonActionPerformed(evt);
            }
        });

        IPtext.setText("Enter the host IP");
        IPtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IPtextActionPerformed(evt);
            }
        });

        msg_area.setColumns(20);
        msg_area.setRows(5);
        jScrollPane1.setViewportView(msg_area);

        connectButton.setText("Connect");
        connectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonActionPerformed(evt);
            }
        });

        startButton.setText("Start Game");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(createButton)
                                                .addGap(34, 34, 34)
                                                .addComponent(joinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(IPtext, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(connectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(joinButton, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                                        .addComponent(IPtext, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(connectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    // decides what happens when the join action is pressed
    // the join lobby button just connnects to the server of the host ip and starts the server of the host
    private void joinButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        try {
            users = new ArrayList();
            if (!IPtext.getText().equals("")) {
                msg_area.append("You have set the host IP to " + IPtext.getText() + "\n");
                host_ip = IPtext.getText();
                users.add(host_ip);
                own_ip = InetAddress.getLocalHost().toString();
                own_ip = own_ip.substring(own_ip.lastIndexOf('/')+1);
                System.out.println(own_ip);
                Thread starter = new Thread(new ServerStart());
                starter.start();
                msg_area.append("Established connection to host" + "\n");
                Socket user = new Socket(host_ip, 2222);

                PrintWriter writer = new PrintWriter(user.getOutputStream());
                Thread listener = new Thread(new ClientHandler(user, writer));
                listener.start();
            } else {
                msg_area.append("No IP has been given" + "\n");
            }
        } catch (Exception e) {
            msg_area.append("Initial connectivity problems" + "\n");
            e.printStackTrace();
        }
    }

    // create lobby is pressed by the host and it starts his own server and he is ready to receive connections
    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        try {
            msg_area.append("Server started...\n");
            connectToEveryone = 1;
            msg_area.append("Ready to receive all the IPs" + "\n");
            playerNumber = 0;
            msg_area.append("You have been assigned as the 0 player" + "\n");
            own_ip = InetAddress.getLocalHost().toString();
            own_ip = own_ip.substring(own_ip.lastIndexOf('/')+1);
            System.out.println(own_ip);
            Thread starter = new Thread(new ServerStart());
            starter.start();
        }
        catch (Exception e)
        {
            msg_area.append("There was some problem in creating a lobby" + "\n");
        }
    }

    private void IPtextActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    // creates and connects sockets to the ip's in the users array list
    private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        handleConnections();
    }

    // this button starts the game and sends the start command to all the users
    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        tellEveryone("START");
        lastLoopTime = System.nanoTime();
        System.out.println(playerNumber);
        board = new MultiplayerBoard(playerNumber);
        // sets the AI for the non user bats
        for(int i = users.size();i<4;i++)
        {
            board.bats[i].AI = true;
        }
        // renders the game
        JFrame frame = new JFrame("Game");
        frame.setContentPane(board);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(400,400);
        frame.setResizable(false);
        frame.pack();
        frame.setVisible(true);
        float[] vel = {2,-3};
        board.setBallVelocity(vel);
        ActionListener taskPerformer = new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                int[] pos = new int[2];
                int[] lives = new int[4];
                pos = board.getPlayerBatPosition(playerNumber);
                lives = board.getLives();
                long delta = System.nanoTime() - lastLoopTime;
                ball = board.getBallPosition();
                bats[playerNumber][0]=pos[0];
                // only the host can send the position of ball and the lives
                bats[playerNumber][1]=pos[1];if(delta > 500000000) {
                    tellEveryone("MoveB" + " " + pos[0] + " " + pos[1] + " " + playerNumber + " " + ball[0] + " " + ball[1]
                            +" "+lives[0]+" "+lives[1]+" "+lives[2]+" "+lives[3]);
                }
                else
                    tellEveryone("Move" +" "+pos[0]+" "+pos[1]+" "+playerNumber);
                board.Update(false,ball,bats);
            }
        };
        timer=new Timer(DELAY,taskPerformer);
        timer.start();

    }

    // this class handles all the server starts
    public class ServerStart implements Runnable {

        @Override
        public void run() {
            clientOutputStreams = new ArrayList();
            users = new ArrayList();
            int player = 1 ;
            String sent_ip;
            try {
                // the next line creates the server for the user
                ServerSocket serverSock = new ServerSocket(2222);
                msg_area.append("Server is at IP = "
                        + serverSock.getInetAddress().getLocalHost().getHostAddress()
                        + " and the port is = 2222" + "\n");

                if (connectToEveryone == 1) {
                    host_ip = serverSock.getInetAddress().getLocalHost().getHostAddress();
                    users.add(host_ip);
                }

                while (true) {
                    // clientSock is the socket that stores the information for the connections received
                    Socket clientSock = serverSock.accept();
                    PrintWriter writer = new PrintWriter(clientSock.getOutputStream());
                    clientOutputStreams.add(writer);
                    if (!users.contains(clientSock.getInetAddress().getHostAddress())) {
                        users.add(clientSock.getInetAddress().getHostAddress());
                    }
                    // we get the connections and the players are assigned the values in increasing order starting from 0
                    msg_area.append("Got a connection from "
                            + clientSock.getInetAddress().getHostAddress() + "\n");
                    if(own_ip.equals(host_ip)) {
                        tellEveryone("Player" + " " + player + " " + clientSock.getInetAddress().getHostAddress());
                        msg_area.append("Assigned" + clientSock.getInetAddress().getHostAddress()
                                + " " + player + " " + "player");
                        player = player + 1;
                    }
                    // the user sends everyone the ip's he has received
                    if (own_ip.equals(host_ip)) {
                        Iterator it = users.iterator();
                        while (it.hasNext()) {
                            sent_ip = (String) it.next();
                            msg_area.append("Sent the IP " + sent_ip + "\n");
                            tellEveryone("IP:" + " " + sent_ip);
                        }
                    }
                    Thread listener = new Thread(new ServerHandler(clientSock, writer));
                    listener.start();

                }
            } catch (Exception ex) {
                msg_area.append("Error making a connection. \n");
                ex.printStackTrace();
            }
        }
    }

    // this is the class that handles all the sockets to all the server sockets of other users
    public class ClientHandler implements Runnable {

        BufferedReader reader;
        Socket sock;
        PrintWriter client;

        public ClientHandler(Socket clientSocket, PrintWriter user) {
            client = user;
            try {
                sock = clientSocket;
                InputStreamReader isReader = new InputStreamReader(sock.getInputStream());
                reader = new BufferedReader(isReader);
            } catch (Exception ex) {
                msg_area.append("Unexpected error... \n");
            }

        }

        // this function receives the messages and interprets them according to the specified first word
        @Override
        public void run() {
            String message;
            try {
                while ((message = reader.readLine()) != null) {
                    String[] ip_array = message.split("\\s+");
                    // ip is received and the users adds it to his users ArrayList
                    if (ip_array[0].equals("IP:")) {

                        if (!users.contains(ip_array[1])) {
                            msg_area.append("An IP was received " + ip_array[1] + "\n");
                            users.add(ip_array[1]);
                        }
                    }
                    // receives which player bat he has been assigned
                    else if (ip_array[0].equals("Player"))
                    {
                        if(own_ip.equals(ip_array[2]))
                        {
                            playerNumber = Integer.parseInt(ip_array[1]);
                        }
                    }
                    // receives the command to start and then acts upon it by rendering the game
                    else if (ip_array[0].equals("START"))
                    {
                        board = new MultiplayerBoard(playerNumber);
                        for(int i = users.size();i<4;i++)
                        {
                            board.bats[i].AI = true;
                        }
                        lastLoopTime=System.nanoTime();
                        JFrame frame = new JFrame("Game");
                        frame.setContentPane(board);
                        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                        frame.setSize(400,400);
                        frame.setResizable(false);
                        frame.pack();
                        frame.setVisible(true);
                        float[] vel = {2,-3};
                        board.setBallVelocity(vel);

                        ActionListener taskPerformer = new ActionListener() {
                            public void actionPerformed(ActionEvent evt) {
                                int[] pos = new int[2];
                                int[] lives = new int[4];
                                pos = board.getPlayerBatPosition(playerNumber);
                                lives = board.getLives();
                                bats[playerNumber][0]=pos[0];
                                bats[playerNumber][1]=pos[1];
                                long delta = System.nanoTime() - lastLoopTime;
                                if(own_ip.equals(host_ip)) {
                                    ball=board.getBallPosition();
                                    if(delta > 500000000) {
                                        tellEveryone("MoveB" + " " + pos[0] + " " + pos[1] + " " + playerNumber + " " + ball[0] + " " + ball[1]
                                        +" "+lives[0]+" "+lives[1]+" "+lives[2]+" "+lives[3]);
                                    }
                                    else
                                        tellEveryone("Move" +" "+pos[0]+" "+pos[1]+" "+playerNumber);
                                    board.Update(false,ball,bats);
                                }
                                else {
                                    tellEveryone("Move" + " " + pos[0] + " " + pos[1] + " " + playerNumber);
                                    if(delta > 500000000) {
                                        board.Update(true, ball, bats);
                                    }
                                    else
                                        board.Update(false,ball,bats);
                                }
                            }
                        };
                        timer=new Timer(DELAY,taskPerformer);
                        timer.start();
                    }

                    // command to render the board with the given positions
                    else if(ip_array[0].equals("Move"))
                    {
                            switch (Integer.parseInt(ip_array[3])) {
                                case 0: {
                                    bats[0][0] = Integer.parseInt(ip_array[1]);
                                    bats[0][1] = Integer.parseInt(ip_array[2]);
                                    break;
                                }
                                case 1: {
                                    bats[1][0] = Integer.parseInt(ip_array[1]);
                                    bats[1][1] = Integer.parseInt(ip_array[2]);
                                    break;
                                }
                                case 2: {
                                    bats[2][0] = Integer.parseInt(ip_array[1]);
                                    bats[2][1] = Integer.parseInt(ip_array[2]);
                                    break;
                                }
                                case 3: {
                                    bats[3][0] = Integer.parseInt(ip_array[1]);
                                    bats[3][1] = Integer.parseInt(ip_array[2]);
                                    break;
                                }
                            }
                        }
                    // command of the positions and lives and positions of the ball
                    else if(ip_array[0].equals("MoveB"))
                    {
                        switch (Integer.parseInt(ip_array[3])) {
                            case 0: {
                                bats[0][0] = Integer.parseInt(ip_array[1]);
                                bats[0][1] = Integer.parseInt(ip_array[2]);
                                ball[0]=Float.parseFloat(ip_array[4]);
                                ball[1]=Float.parseFloat(ip_array[5]);
                                int lives[] = new int[4];
                                lives[0] = Integer.parseInt(ip_array[6]);
                                lives[1] = Integer.parseInt(ip_array[7]);
                                lives[2] = Integer.parseInt(ip_array[8]);
                                lives[3] = Integer.parseInt(ip_array[9]);
                                board.setLives(lives);
                                break;
                            }
                            case 1: {
                                bats[1][0] = Integer.parseInt(ip_array[1]);
                                bats[1][1] = Integer.parseInt(ip_array[2]);
                                ball[0]=Float.parseFloat(ip_array[4]);
                                ball[1]=Float.parseFloat(ip_array[5]);
                                int lives[] = new int[4];
                                lives[0] = Integer.parseInt(ip_array[6]);
                                lives[1] = Integer.parseInt(ip_array[7]);
                                lives[2] = Integer.parseInt(ip_array[8]);
                                lives[3] = Integer.parseInt(ip_array[9]);
                                board.setLives(lives);
                                break;
                            }
                            case 2: {
                                bats[2][0] = Integer.parseInt(ip_array[1]);
                                bats[2][1] = Integer.parseInt(ip_array[2]);
                                ball[0]=Float.parseFloat(ip_array[4]);
                                ball[1]=Float.parseFloat(ip_array[5]);
                                int lives[] = new int[4];
                                lives[0] = Integer.parseInt(ip_array[6]);
                                lives[1] = Integer.parseInt(ip_array[7]);
                                lives[2] = Integer.parseInt(ip_array[8]);
                                lives[3] = Integer.parseInt(ip_array[9]);
                                board.setLives(lives);
                                break;
                            }
                            case 3: {
                                bats[3][0] = Integer.parseInt(ip_array[1]);
                                bats[3][1] = Integer.parseInt(ip_array[2]);
                                ball[0]=Float.parseFloat(ip_array[4]);
                                ball[1]=Float.parseFloat(ip_array[5]);
                                int lives[] = new int[4];
                                lives[0] = Integer.parseInt(ip_array[6]);
                                lives[1] = Integer.parseInt(ip_array[7]);
                                lives[2] = Integer.parseInt(ip_array[8]);
                                lives[3] = Integer.parseInt(ip_array[9]);
                                board.setLives(lives);
                                break;
                            }
                        }
                    }

                    else {
                        msg_area.append("Received: " + message + "\n");
                    }
                }
            } catch (Exception ex) {
                msg_area.append("Lost a connection. \n");
                ex.printStackTrace();
                clientOutputStreams.remove(client);
            }
        }
    }
    // connects to the ips in the users ArrayList
    public void handleConnections() {
        Iterator it = users.iterator();

        while (it.hasNext()) {
            try {
                String user_ip = (String) it.next();
                if (!user_ip.equals(own_ip)
                        && !user_ip.equals(host_ip)) {
                    Socket user = new Socket(user_ip, 2222);
                    msg_area.append("Established connection with" + user_ip + "\n");
                    PrintWriter writer = new PrintWriter(user.getOutputStream());
                    Thread listener = new Thread(new ClientHandler(user, writer));
                    listener.start();
                }
            } catch (Exception ex) {
                ex.printStackTrace();
                msg_area.append("Error contacting everyone. \n");
            }
        }
    }

    // this class handles the server Sockets
    public class ServerHandler implements Runnable {

        BufferedReader reader;
        Socket sock;
        PrintWriter client;
        String ip;

        public ServerHandler(Socket clientSocket, PrintWriter user) {
            client = user;
            try {
                sock = clientSocket;
                InputStreamReader isReader = new InputStreamReader(sock.getInputStream());
                reader = new BufferedReader(isReader);
                ip = sock.getInetAddress().getHostAddress();
                System.out.println("ip received" + ip);
            } catch (Exception ex) {
                msg_area.append("Unexpected error... \n");
            }

        }

        @Override
        public void run() {
            String message;
            try {
                while ((message = reader.readLine()) != null) {
                    System.out.println("Message is" + message);
                }
            }
            // major exception handling whenever one user leaves we know the ip and add the AI inplace
            // also handles the cases if the host disconnects
            catch (Exception ex) {
                msg_area.append("Lost a connection. \n");
                msg_area.append("IP that was lost is " + ip + "\n");
                int index = users.indexOf(ip);
                board.bats[index].AI = true;
                int new_host = 0;
                if(ip.equals(host_ip))
                {
                    for(int i =0 ;i<4 ;i++)
                    {
                        if(!board.bats[i].AI)
                        {
                            new_host = i;
                            break;
                        }
                    }

                    host_ip = (String)users.get(new_host);
                }
                clientOutputStreams.remove(client);
            }
        }
    }

    // sends the given messages to everyone by the output streams ArrayList
    public void tellEveryone(String message) {
        Iterator it = clientOutputStreams.iterator();

        while (it.hasNext()) {
            try {
                PrintWriter writer = (PrintWriter) it.next();
                writer.println(message);
                writer.flush();

            } catch (Exception ex) {
                msg_area.append("Error telling everyone. \n");
            }
        }
    }


    // Variables declaration - do not modify
    private javax.swing.JTextField IPtext;
    private javax.swing.JButton connectButton;
    private javax.swing.JButton createButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton joinButton;
    private static javax.swing.JTextArea msg_area;
    private javax.swing.JButton startButton;
    // End of variables declaration
}

